엔티티 채팅방 && 채팅내용 생성
my-neighborhood-solver/nsBackEnd pull request #44
Opened 2023-08-01 13:29 UTC by jisu9169

## Motivations 🔥
- 

<br/>

## key Changes ⭐️
- 그룹채팅은 없애고 errand 당 한명당 sender 한명 일대일 채팅
- 채팅방 && 채팅 내용 엔티티 생성

<br/>

## To Reviewers 🙏
- gyureal
- SeokCheol-Lee

<br/>

2023-08-01 13:36 UTC, SeokCheol-Lee approved these changes

2023-08-01 13:36 UTC, SeokCheol-Lee commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  @JoinColumn(name = "errand_id", referencedColumnName = "id")
referencedColumnName을 사용하시는 이유가 있을까요?

2023-08-01 17:10 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  @JoinColumn(name = "errand_id", referencedColumnName = "id")
referencedColumnName 기본값인 'id'와 매핑하려고 사용했는데, 찾아보니까 유지보수의 어려움이 있다고하네요. 
해당 설정을 제거하도록 하겠습니다. 이후에는 기본값을 사용하지 않고 명시적으로 참조할 필드를 지정하는 방식으로 진행하겠습니다. 감사합니다.

2023-08-02 13:58 UTC, gyureal requested changes
ERD와 객체 설계가 다른 부분이 있는 것 같습니다.
ERD를 수정해 주시던지, 객체를 수정해 주시던지 해서 맞추어 주셔야 될 것 같습니다.
그리고 새로 바꾼 엔티티 설계에 대해 설명이 조금 필요할 것 같습니다.

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingContent.java
> +  private LocalDateTime contentTime;
contentTime 은 무엇인가요?

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  @JoinColumn( name = "member_id" )
JoinColumn의 name 값을 표시하면 해당 이름으로 컬럼명이 표시되는 거 같은데 맞나요?

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  private LocalDateTime createAt;
global에 있는 BaseTimeEntity를 사용하시면 해당 속성이 없어져도 될 것 같습니다

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  private LocalDateTime exitTimeMember;
위 두 속성은 어떤 의미인가요?

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +      Long sender_id) {
어플리케이션 단에서는 _언더바로 구분하지말고, camelCase로 변수명을 지정해주세요 (errandId, senderId)

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/repository/ChattingRoomRepository.java
> +  ChattingRoom findByErrand_MemberAndSender(Errand errand, Member sender);
해당 메서드는 최대 하나의 값만 반환하나요? 두개 이상의 값이 반환되면 에러를 반환할 것 같습니다. 또한 하나의 값만 반환한다면, 값이 없을 경우를 가정해서 Optional으로 반환 받으면 일관성 있을 것 같습니다

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +          .body(ChattingRoomCreateResponse.from(chattingRoom));
ResponseEntity는 최종응답이니 컨트롤러 단(표현 계층)에 구현되어야 한다고 생각합니다.
그리고 HttpsStauts.Conflict 는 에러인거 같은데, 에러 일때 에러 메세지만 반환해야 한다고 생각합니다.
또한, exception handling 은 global의 공통 exceptionHandler에서 담당하고 있습니다

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    return ResponseEntity.ok().body(ChattingRoomCreateResponse.from(ChattingRoomSave));
ResponseEntity는 표현계층에 있어야 할 것 같습니다

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    }
해당 상황에서는 .orElseThrows 를 더 많이 사용하는 것 같습니다.

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/dto/ChattingRoomCreateRequest.java
> +  private Long sender_Id;
어플리케이션 단에는 camelCase로 작성부탁드립니다

2023-08-02 13:58 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/web/ChattingRoomController.java
> +        .createChattingRoom(request.getErrand_Id(), request.getSender_Id());
예외는 진짜 예외인 상황에 터트려야한다고 생각합니다. 프로세스의 일부에 분기문 역할로 사용되어서는 안됩니다.

참고) [이펙티브 자바, 쉽게 정리하기 - item 69. 예외는 진짜 예외 상황에만 사용하라](https://jake-seo-dev.tistory.com/564)

2023-08-03 07:16 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingContent.java
> +  private LocalDateTime contentTime;
채팅한 시간을 나타내려고했습니다. BaseTimeEntity extends 했습니다.

2023-08-03 07:16 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  @JoinColumn( name = "member_id" )
네 member_id 라는 컬럼이 생성되고 member 테이블의 주요 키인 id를 참조하는걸로 알고 있습니다.

2023-08-03 07:16 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  private LocalDateTime createAt;
넵 사용했습니다.

2023-08-03 07:16 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/entity/ChattingRoom.java
> +  private LocalDateTime exitTimeMember;
채팅방 나가기를 만들려고했습니다. 제거했습니다.

2023-08-03 07:17 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +      Long sender_id) {
넵 변경하였습니다.

2023-08-03 07:17 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +          .body(ChattingRoomCreateResponse.from(chattingRoom));
넵 변경하였습니다.

2023-08-03 07:17 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    return ResponseEntity.ok().body(ChattingRoomCreateResponse.from(ChattingRoomSave));
넵 변경하였습니다.

2023-08-03 07:17 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    }
변경하였습니다.

2023-08-03 07:17 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/dto/ChattingRoomCreateRequest.java
> +  private Long sender_Id;
카멜 표기법으로 변경하였습니다.

2023-08-03 14:45 UTC, prebird approved these changes

2023-08-07 09:37 UTC, closed without merging