채팅 전체 조회 && 단건 조회 테스트코드
my-neighborhood-solver/nsBackEnd pull request #69
Opened 2023-08-08 13:21 UTC by jisu9169

## Motivations 🔥
- 

<br/>

## key Changes ⭐️
- 채팅방 전체 조회
- 채팅방 단건 조회
- 채팅방 전체 조회 테스트코드 
<br/>

## To Reviewers 🙏
- gyureal
- SeokCheol-Lee
<br/>

2023-08-09 10:20 UTC, gyureal requested changes
간단히 리뷰 드려 보았습니다.
API 테스트는 해보셨나요?

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/controller/ChattingRoomController.java
> +  @GetMapping("/memberId={memberId}")
path parameter 설정 방법이 잘못 되었습니다.
Path parameter는 = 으로 설정하지 않고 / 내에 경로로 명시합니다.
"/memberId={memberId}" -> "/{memberId}"

Query Parameter를 사용하고 싶으신 거라면
@RequestParam 어노테이션을 사용하여야합니다.

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/controller/ChattingRoomController.java
> +  @GetMapping("/{roomId}/memberId={memberId}")
memberId 는 RequestParam 을 사용해주세요

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/repository/ChattingContentRepository.java
> +  int countBySenderNotAndIsReadAndChattingRoom(Member member1, boolean b, ChattingRoom chattingRoom1);
b 보다 의미있는 단어로 명시해주세요 ex) is___

member1 과 chattingRoom1 에서 1은 빼주셔돌 될 것 같아요

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +        .findByErrand_Errander_IdOrSenderId(memberId, memberId);
errander 와 sender 에 동일한 값이 들어가는데 맞나요?

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +      int isRead;
is__ 는 보통 boolean 타입을 명시할 때 사용됩니다. readCount 와 같이 숫자임을 명시할 수 있는 값으로 바꿔주시면 좋을 것 같아요

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    if (!ChattingRoomValidationUtil(roomId, memberId)) {
Util 이라는 네이밍은 유틸 클래스에 쓰이는 네이밍입니다. 메서드에는 사용하지 않습니다.
메서드는 동사로 명시하는 것이 좋습니다.
ex) validMemberInRoom (회원이 채팅방에 있는지 유효성 검사 직역)

2023-08-09 10:20 UTC, gyureal commented on src/main/java/com/zerobase/nsbackend/chatting/dto/ChatContentResponse.java
> +  public static ChatContentResponse to(ChattingContent chattingContent){
보통 이럴때는 from 이라는 네이밍을 사용합니다. ( ~ 객체로 부터 해당 객체를 생성 한다는 의미)

2023-08-09 16:03 UTC, jisu9169 commented
API 테스트 Postman으로 해봤습니다 데이터베이스의 임이의 값 넣어서 잘나온것까지확인했습니다.

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/repository/ChattingContentRepository.java
> +  int countBySenderNotAndIsReadAndChattingRoom(Member member1, boolean b, ChattingRoom chattingRoom1);
변경하였습니다.

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +      int isRead;
변경하였습니다

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +    if (!ChattingRoomValidationUtil(roomId, memberId)) {
validMemberInRoom  예시로 변경하였습니다.

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/dto/ChatContentResponse.java
> +  public static ChatContentResponse to(ChattingContent chattingContent){
변경하였습니다

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/domain/service/ChattingRoomService.java
> +        .findByErrand_Errander_IdOrSenderId(memberId, memberId);
저도 처음에 And로 했다가 채팅방 memberId가 서로 같을수가없어서 and -> or로 변경하였습니다.
errander _id 값 도 받아지고 sender _id 값도 받아오려고했습니다.

2023-08-10 11:40 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/controller/ChattingRoomController.java
> +  @GetMapping("/memberId={memberId}")
변경했습니다.

2023-08-10 11:41 UTC, jisu9169 commented on src/main/java/com/zerobase/nsbackend/chatting/controller/ChattingRoomController.java
> +  @GetMapping("/{roomId}/memberId={memberId}")
변경했습니다-

2023-08-10 12:15 UTC, SeokCheol-Lee approved these changes

2023-08-10 12:39 UTC, gyureal approved these changes

2023-08-10 13:07 UTC, merged